'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { ArrowDownTrayIcon, DocumentTextIcon } from '@heroicons/react/24/outline';
import toast from 'react-hot-toast';

interface PDFGeneratorProps {
  data: any;
  results: any;
  onGenerate?: () => void;
}

export function PDFGenerator({ data, results, onGenerate }: PDFGeneratorProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  const generatePDF = async () => {
    setIsGenerating(true);
    
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      
      // Header
      pdf.setFontSize(24);
      pdf.setFont('helvetica', 'bold');
      pdf.text('CreditLens Assessment Report', pageWidth / 2, 20, { align: 'center' });
      
      // Date
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth / 2, 30, { align: 'center' });
      
      // Eligibility Section
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Assessment Results', 20, 50);
      
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Eligibility: ${results.eligibility}`, 20, 65);
      pdf.text(`Risk Probability: ${(results.pred_prob * 100).toFixed(1)}%`, 20, 75);
      pdf.text(`Recommended Interest Rate: ${results.recommended_interest_rate}%`, 20, 85);
      
      // Repayment Schedule
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Repayment Schedule', 20, 105);
      
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Term: ${results.repayment_schedule.term_months} months`, 20, 120);
      pdf.text(`Monthly Payment: $${results.repayment_schedule.monthly_installment.toLocaleString()}`, 20, 130);
      pdf.text(`Total Payment: $${results.repayment_schedule.total_payment.toLocaleString()}`, 20, 140);
      pdf.text(`Total Interest: $${results.repayment_schedule.total_interest.toLocaleString()}`, 20, 150);
      
      // Risk Factors
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Key Risk Factors', 20, 170);
      
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      results.decision_reasoning.forEach((factor: any, index: number) => {
        const yPos = 185 + (index * 10);
        pdf.text(`• ${factor.description} (${factor.impact_pct_pts.toFixed(1)}% impact)`, 20, yPos);
      });
      
      // Actionable Tips
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Recommendations', 20, 220);
      
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      results.actionable_tips.forEach((tip: string, index: number) => {
        const yPos = 235 + (index * 10);
        pdf.text(`• ${tip}`, 20, yPos);
      });
      
      // Footer
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'italic');
      pdf.text('This report is generated by CreditLens AI-powered credit assessment system.', pageWidth / 2, pageHeight - 20, { align: 'center' });
      pdf.text('For questions, contact support@creditlens.com', pageWidth / 2, pageHeight - 15, { align: 'center' });
      
      // Save the PDF
      pdf.save(`creditlens-assessment-${new Date().toISOString().split('T')[0]}.pdf`);
      
      toast.success('PDF report generated successfully!');
      onGenerate?.();
      
    } catch (error) {
      console.error('PDF generation error:', error);
      toast.error('Failed to generate PDF. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <motion.button
      onClick={generatePDF}
      disabled={isGenerating}
      className="flex items-center px-6 py-3 bg-primary-600 text-white rounded-lg hover:bg-primary-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 transform hover:scale-105"
      whileHover={{ scale: 1.05 }}
      whileTap={{ scale: 0.95 }}
    >
      {isGenerating ? (
        <>
          <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-2"></div>
          Generating...
        </>
      ) : (
        <>
          <DocumentTextIcon className="w-5 h-5 mr-2" />
          Generate PDF Report
        </>
      )}
    </motion.button>
  );
}
